services:
  database:
    image: postgres:15  # Use a specific PostgreSQL version if needed
    container_name: hsthma_database
    ports:
      - "5432:5432"  # Map PostgreSQL default port
    environment:
      POSTGRES_USER: postgres  # Matches the username in your connection string
      POSTGRES_PASSWORD: admin  # Matches the password in your connection string
      POSTGRES_DB: hsthma  # Matches the database name in your connection string
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data across restarts
    restart: unless-stopped

volumes:
  db_data:
